set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN W19 [get_ports Dot]
set_property IOSTANDARD LVCMOS33 [get_ports Dot]
set_property PULLDOWN true [get_ports Dot]

set_property PACKAGE_PIN T17 [get_ports Dash]
set_property IOSTANDARD LVCMOS33 [get_ports Dash]
set_property PULLDOWN true [get_ports Dash]
set_property PACKAGE_PIN J1 [get_ports speaker1]
set_property PACKAGE_PIN L2 [get_ports speaker2]
set_property IOSTANDARD LVCMOS33 [get_ports speaker1]
set_property IOSTANDARD LVCMOS33 [get_ports speaker2]
