#set_property IOSTANDARD LVCMOS33 [get_ports Dot]
#set_property IOSTANDARD LVCMOS33 [get_ports Dash]
#set_property IOSTANDARD LVCMOS33 [get_ports BuzzerSig]
#set_property PACKAGE_PIN W19 [get_ports Dot]
#set_property PACKAGE_PIN T17 [get_ports Dash]
#set_property PACKAGE_PIN J1 [get_ports BuzzerSig]
#set_property PULLDOWN true [get_ports Dot]
#set_property PULLDOWN true [get_ports Dash]

#set_property PACKAGE_PIN L1 [get_ports LED]
#set_property IOSTANDARD LVCMOS33 [get_ports LED]

#set_property PACKAGE_PIN W5 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN W19 [get_ports Dot]
set_property IOSTANDARD LVCMOS33 [get_ports Dot]
set_property PULLDOWN true [get_ports Dot]

set_property PACKAGE_PIN T17 [get_ports Dash]
set_property IOSTANDARD LVCMOS33 [get_ports Dash]
set_property PULLDOWN true [get_ports Dash]
#set_property PACKAGE_PIN J1 [get_ports speaker1]
#set_property PACKAGE_PIN L2 [get_ports speaker2]
#set_property IOSTANDARD LVCMOS33 [get_ports speaker1]
#set_property IOSTANDARD LVCMOS33 [get_ports speaker2]

set_property PACKAGE_PIN R2 [get_ports Clear]
set_property PACKAGE_PIN T1 [get_ports Reset]
set_property PACKAGE_PIN T18 [get_ports EndSeq]
set_property PACKAGE_PIN U18 [get_ports Space]
set_property PACKAGE_PIN U17 [get_ports Enter]
set_property IOSTANDARD LVCMOS33 [get_ports Clear]
set_property IOSTANDARD LVCMOS33 [get_ports EndSeq]
set_property IOSTANDARD LVCMOS33 [get_ports Enter]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports Space]
set_property PULLDOWN true [get_ports Space]
set_property PULLDOWN true [get_ports Enter]
set_property PULLDOWN true [get_ports EndSeq]
set_property PACKAGE_PIN L1 [get_ports {translatedCharacters[127]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[127]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[126]}]
set_property PACKAGE_PIN P1 [get_ports {translatedCharacters[126]}]
set_property PACKAGE_PIN N3 [get_ports {translatedCharacters[125]}]
set_property PACKAGE_PIN P3 [get_ports {translatedCharacters[124]}]
set_property PACKAGE_PIN U3 [get_ports {translatedCharacters[123]}]
set_property PACKAGE_PIN W3 [get_ports {translatedCharacters[122]}]
set_property PACKAGE_PIN V3 [get_ports {translatedCharacters[121]}]
set_property PACKAGE_PIN V13 [get_ports {translatedCharacters[120]}]
set_property PACKAGE_PIN V14 [get_ports {translatedCharacters[119]}]
set_property PACKAGE_PIN U14 [get_ports {translatedCharacters[118]}]
set_property PACKAGE_PIN U15 [get_ports {translatedCharacters[117]}]
set_property PACKAGE_PIN W18 [get_ports {translatedCharacters[116]}]
set_property PACKAGE_PIN V19 [get_ports {translatedCharacters[115]}]
set_property PACKAGE_PIN U19 [get_ports {translatedCharacters[114]}]
set_property PACKAGE_PIN E19 [get_ports {translatedCharacters[113]}]
set_property PACKAGE_PIN U16 [get_ports {translatedCharacters[112]}]

set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[125]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[124]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[112]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[113]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[114]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[115]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[116]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[117]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[123]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[122]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[121]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[120]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[119]}]
set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[118]}]
