set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN W19 [get_ports Dot]
set_property IOSTANDARD LVCMOS33 [get_ports Dot]
set_property PULLDOWN true [get_ports Dot]

set_property PACKAGE_PIN T17 [get_ports Dash]
set_property IOSTANDARD LVCMOS33 [get_ports Dash]
set_property PULLDOWN true [get_ports Dash]

set_property PACKAGE_PIN T18 [get_ports EndSeq]
set_property IOSTANDARD LVCMOS33 [get_ports EndSeq]
set_property PULLDOWN true [get_ports EndSeq]

set_property PACKAGE_PIN U18 [get_ports Space]
set_property IOSTANDARD LVCMOS33 [get_ports Space]
set_property PULLDOWN true [get_ports Space]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets Enter_IBUF]

set_property PACKAGE_PIN R2 [get_ports Clear]
set_property IOSTANDARD LVCMOS33 [get_ports Clear]

set_property PACKAGE_PIN T1 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]

set_property PACKAGE_PIN U17 [get_ports Enter]
set_property IOSTANDARD LVCMOS33 [get_ports Enter]
set_property PULLDOWN true [get_ports Enter]

set_property PACKAGE_PIN J1 [get_ports dot_buzzer]
set_property PACKAGE_PIN L2 [get_ports dash_buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports dot_buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports dash_buzzer]

#set_property PACKAGE_PIN L1 [get_ports {o_sequence[9]}]
#set_property PACKAGE_PIN P1 [get_ports {o_sequence[8]}]
set_property PACKAGE_PIN N3 [get_ports {characters[7]}]
set_property PACKAGE_PIN P3 [get_ports {characters[6]}]
set_property PACKAGE_PIN U3 [get_ports {characters[5]}]
set_property PACKAGE_PIN W3 [get_ports {characters[4]}]
set_property PACKAGE_PIN V3 [get_ports {characters[3]}]
set_property PACKAGE_PIN V13 [get_ports {characters[2]}]
set_property PACKAGE_PIN V14 [get_ports {characters[1]}]
set_property PACKAGE_PIN U14 [get_ports {characters[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sequence[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sequence[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {characters[0]}]

set_property PACKAGE_PIN U19 [get_ports spa_end]
set_property IOSTANDARD LVCMOS33 [get_ports spa_end]
set_property PACKAGE_PIN E19 [get_ports sent]
set_property IOSTANDARD LVCMOS33 [get_ports sent]
set_property PACKAGE_PIN U16 [get_ports storageSent]
set_property IOSTANDARD LVCMOS33 [get_ports storageSent]

#set_property PACKAGE_PIN L1 [get_ports {translatedCharacters[15]}]
#set_property PACKAGE_PIN P1 [get_ports {translatedCharacters[14]}]
#set_property PACKAGE_PIN N3 [get_ports {translatedCharacters[13]}]
#set_property PACKAGE_PIN P3 [get_ports {translatedCharacters[12]}]
#set_property PACKAGE_PIN U3 [get_ports {translatedCharacters[11]}]
#set_property PACKAGE_PIN W3 [get_ports {translatedCharacters[10]}]
#set_property PACKAGE_PIN V3 [get_ports {translatedCharacters[9]}]
#set_property PACKAGE_PIN V13 [get_ports {translatedCharacters[8]}]
#set_property PACKAGE_PIN V14 [get_ports {translatedCharacters[7]}]
#set_property PACKAGE_PIN U14 [get_ports {translatedCharacters[6]}]
#set_property PACKAGE_PIN U15 [get_ports {translatedCharacters[5]}]
#set_property PACKAGE_PIN W18 [get_ports {translatedCharacters[4]}]
#set_property PACKAGE_PIN V19 [get_ports {translatedCharacters[3]}]
#set_property PACKAGE_PIN U19 [get_ports {translatedCharacters[2]}]
#set_property PACKAGE_PIN E19 [get_ports {translatedCharacters[1]}]
#set_property PACKAGE_PIN U16 [get_ports {translatedCharacters[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {translatedCharacters[8]}]

#set_property PACKAGE_PIN V17 [get_ports Dash]
#set_property PACKAGE_PIN V16 [get_ports Dot]
#set_property IOSTANDARD LVCMOS33 [get_ports Dash]
#set_property IOSTANDARD LVCMOS33 [get_ports Dot]